name: notify

on:
  push:
    branches:
      - '**'
  fork:
  watch:
    types:
      - started
  issues:
    types:
      - opened
      - closed
      - reopened
      - locked
      - unlocked
  issue_comment:
    types:
      - created
      - deleted
  pull_request:
    types:
      - opened
      - closed
      - reopened
      - locked
      - unlocked
      - synchronize
  pull_request_review_comment:
    types:
      - created
      - deleted
  release:
    types:
      - published
      - released

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.NOTIFY_BOT_TOKEN }}
      CHAT_ID: ${{ secrets.NOTIFY_CHAT_ID }}
    steps:
      - name: Notify the event on Telegram
        if: ${{ env.BOT_TOKEN != '' && env.CHAT_ID != '' }}
        uses: EverythingSuckz/github-telegram-notify@main
        with:
          bot_token: '${{ env.BOT_TOKEN }}'
          chat_id: '${{ env.CHAT_ID }}'
